# 사이트 설정

# 테마를 가져오기
theme: jekyll-theme-chirpy

# 웹페이지의 언어 설정 › http://www.lingoes.net/en/translator/langcode.htm
# 만약 `_data/locales` 폴더의 파일 이름과 동일하면 레이아웃 언어도 변경됩니다.
# 그렇지 않으면 레이아웃 언어는 기본값인 'en'을 사용합니다.
lang: ko

# 타임존 설정 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Seoul

# jekyll-seo-tag 설정 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: 여우비 개발실 # 메인 제목

tagline: A text-focused Jekyll theme # 부제목으로 표시됩니다.

description: >- # SEO 메타 및 Atom 피드에 사용됩니다.
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# 사이트의 프로토콜 및 호스트명을 입력하세요.
# 예: 'https://username.github.io', 끝에 '/'를 포함하지 마십시오.
url: "https://Dev-Foxx.github.io"

github:
  username: Dev-Foxx # GitHub 사용자 이름으로 변경하세요.

# twitter:
#   username: twitter_username # Twitter 사용자 이름으로 변경하세요.

social:
  # 전체 이름으로 변경하세요.
  # 게시물의 기본 작성자 및 푸터의 저작권 소유자로 표시됩니다.
  name: Dev_Fox
  email: Developer_Fox@outlook.com # 이메일 주소로 변경하세요.
  links:
    # 첫 번째 요소는 저작권 소유자의 링크로 사용됩니다.
    # - https://twitter.com/username # Twitter 홈페이지로 변경하세요.
    - https://github.com/Dev-Foxx # GitHub 홈페이지로 변경하세요.
    # 아래 주석을 해제하여 추가 소셜 링크를 추가하세요.
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 사이트 인증 설정
webmaster_verifications:
  google: # Google 인증 코드를 입력하세요.
  bing: # Bing 인증 코드를 입력하세요.
  alexa: # Alexa 인증 코드를 입력하세요.
  yandex: # Yandex 인증 코드를 입력하세요.
  baidu: # Baidu 인증 코드를 입력하세요.
  facebook: # Facebook 인증 코드를 입력하세요.

# ↑ --------------------------
# `jekyll-seo-tag` 설정의 끝

# 웹 분석 설정
analytics:
  google:
    id: # Google Analytics ID를 입력하세요.
  goatcounter:
    id: # GoatCounter ID를 입력하세요.
  umami:
    id: # Umami ID를 입력하세요.
    domain: # Umami 도메인을 입력하세요.
  matomo:
    id: # Matomo ID를 입력하세요.
    domain: # Matomo 도메인을 입력하세요.
  cloudflare:
    id: # Cloudflare 웹 분석 토큰을 입력하세요.
  fathom:
    id: # Fathom 사이트 ID를 입력하세요.

# 페이지 조회수 설정
pageviews:
  provider: # 현재 'goatcounter'만 지원합니다.

# 선호하는 색상 테마 설정
#
# 참고: 비워 두면 기본적으로 시스템 선호 색상을 따르며,
# 왼쪽 하단의 사이드바에서 다크 및 라이트 테마를 전환할 수 있는 토글이 표시됩니다.
#
# 사용 가능한 옵션:
#
#     light — 라이트 색상 테마 사용
#     dark — 다크 색상 테마 사용
#
theme_mode: # [light | dark]

# 미디어 리소스의 CDN 엔드포인트
# 주의: 지정하면 모든 미디어 리소스 경로(사이트 아바타, 게시물 이미지, 오디오 및 비디오 파일)가 '/로 시작하는 경로에 CDN URL이 추가됩니다.'
#
# 예: 'https://cdn.com'
cdn:

# 사이드바에 표시되는 아바타. 로컬 또는 CORS 리소스를 지원합니다.
avatar: /assets/img/avatar.png

# SEO `og:image` 메타 태그에 사용되는 사이트 전반의 소셜 미리보기 이미지 URL.
# 이는 프런트 매터의 맞춤 `page.image`로 재정의할 수 있습니다.
social_preview_image: # 문자열, 로컬 또는 CORS 리소스

# 게시물의 TOC(목차)에 대한 전역 스위치. 비워 두면 비활성화됩니다.
toc: true

comments:
  # 게시물 댓글 시스템의 전역 스위치. 비워 두면 비활성화됩니다.
  provider: # [disqus | utterances | giscus]
  # 제공자 옵션은 다음과 같습니다:
  disqus:
    shortname: # Disqus 단축 이름을 입력하세요. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances 설정 › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus 옵션 › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # 선택 사항, 기본값은 'pathname'
    strict: # 선택 사항, 기본값은 '0'
    input_position: # 선택 사항, 기본값은 'bottom'
    lang: # 선택 사항, 기본값은 `site.lang`의 값
    reactions_enabled: # 선택 사항, 기본값은 '1'

# 셀프 호스팅 정적 자산, 선택 사항 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # 불리언, 비워 두면 false로 간주됩니다.
    # Jekyll 환경 지정, 비워 두면 모두 적용
    # `assets.self_host.enabled`가 'true'인 경우에만 작동합니다.
    env: # [development | production]

pwa:
  enabled: true # PWA 기능(설치 가능)에 대한 옵션
  cache:
    enabled: true # PWA 오프라인 캐시에 대한 옵션
    # 여기 정의된 경로는 PWA 캐시에서 제외됩니다.
    # 일반적으로 그 값은 현재 웹사이트와 동일한 도메인을 공유하는 다른 웹사이트의 `baseurl`입니다.
    deny_paths:
      # - "/example"  # `<SITE_URL>/example/*`에 매칭되는 URL은 PWA 캐시에 저장되지 않습니다.

paginate: 10

# 사이트의 기본 URL
baseurl: "/Dev-Foxx.github.io"

# MathJax 설정
math:
  enable: true


# ------------ 아래 옵션은 수정하지 않는 것이 좋습니다 ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge 옵션 › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # 여기 빈 문자열은 프로젝트의 모든 파일을 의미합니다.
      type: posts
    values:
      layout: post
      comments: true # 게시물에서 댓글 활성화.
      toc: true # 게시물에서 TOC 열 표시.
      # 아래 매개변수를 수정하지 마십시오.
      # 이 프로젝트의 모든 다른 게시물 링크 코드를 업데이트할 자신이 있는 경우가 아니면 수정하지 마세요.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # `site.collections` 참조
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
